/* Add functionalities */
INSERT INTO HHTEDTFUNCTIONALITY(CODE, DESCRIPTION, CREATED_DATE) VALUES('register-employe', 'Registar empleados', NOW());

/* Add roles */
INSERT INTO HHTEDTROLE(CODE, NAME, CREATED_DATE) VALUES('admin', 'Administrator', NOW());
INSERT INTO HHTEDTROLE(CODE, NAME, CREATED_DATE) VALUES('employee', 'Empleado', NOW());

/* Add functionalities to Role */
INSERT INTO HHTEDTROLFUN(ROLE_ID, FUNCTIONALITY_ID, CREATED_DATE) VALUES (1,1, NOW());

/* Add first admin user */
/* Password: Password01*/
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('admin@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 1, NOW());

/* Add City*/
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('SEVILLA', 1, NOW());

/* Add Position */
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('GERENTE DE CUENTA', 1, NOW());

/* Add Department */
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Comercial', 1, NOW());

/* Add user */
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Alfonso Jaime', 'Boreli Ariosto', '612354785', 1, 1, 1, 1, 1, NOW());