/* Add Cities */
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('BARCELONA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('SAN SEBASTIAN', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('GRANADA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('VALENCIA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('SALAMANCA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('MADRID', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('SANTIAGO DE COMPOSTELA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('GALICIA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('CANTABRIA', 1, NOW());

/* Add Positions */
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('TECHNICAL LEADER', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR PROYECTOS ESTRATÉGICOS', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR GENERAL', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR PEOPLE TRANSFORMATION', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('TECHNICAL LEADER CLOUD SERVICES', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('SERVICE MANAGER', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('RESPONSABLE DEPARTAMENTO DE CONTROL', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR SECTOR PÚBLICO', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR OPERACIONES', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MANAGER RECRUITMENT', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('GESTIÓN DE TALENTO', 1, NOW());

/* Department */
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('ADMINISTRACIÓN', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('CONTROL', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MARKETING Y BUSINESS VALUE', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PMO', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('BU COMUNICACIÓN', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('RECURSOS HUMANOS', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('OPERACIONES', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('TECNOLOGÍAS DIFERENCIALES', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MEDIA LABS', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('FINANZAS Y SOPORTE AL NEGOCIO', 1, NOW());

/* Skills */
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('JAVA', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('.NET', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('ANGULAR', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PHP', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('SPRING BOOT', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MYSQL', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('JPA', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('HIBERNATE', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('REACT', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('SPRING MVC', 1, NOW());

/* Projects */
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('GESTIÓN TRIBUTARIA MADRID', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PORTAL MADRID.ES', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PORTAL SPAIN.INFO', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('TARJETA CIUDADANA ZARAGOZA', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('AYUNTAMIENTO DE VALENCIA', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('ADMINISTRACIÓN ELECTRÓNICA DEL GOBIERNO DE ARAGÓN', 1, NOW());

/* Certifications */
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('FRONTEND ANGULAR', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('VIRTUALIZACIÓNN DE SERVICIOS', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('UX Y UI', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('VIRTUALIZACIÓNN DE SERVICIOS', 1, NOW());

/* Employee */
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('arentero@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Antonio Guillermo', 'Rentero Hereza', '723685412', 2, 2, 2, 2, 1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ebarbed@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Elena Maria', 'Barbed Mutuberria', '723685412', 3, 3, 3, 3, 1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('mgarcia@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Mireya Sarah', 'García Latorre', '723685412', 4, 4, 4, 4, 1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('aesteban@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Adrián Javier', 'Esteban Virto', '723685412', 5, 5, 5, 5, 1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ssantolaria@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Sara Eva', 'Santolaria Menéndez', '723685412', 1, 2, 3, 4, 1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ssantolaria@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Sara Eva', 'Santolaria Menéndez', '723685412', 2, 3, 1, 4, 1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ohierro@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Oliver Sergio', 'Hierro Gil', '723685412', 2, 1, 3, 4, 1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('vsanchez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Víctor Jesús', 'Sanchez Mingote', '723685412', 4, 5, 6, 4, 1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('jmorales@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('José Luis', 'Morales Zapata', '723685412', 4, 5, 6, 4, 1, NOW());


/* Add projects */

INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());

/* */
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());

/* */
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());
