/* Add functionalities */
INSERT INTO HHTEDTFUNCTIONALITY(CODE, DESCRIPTION, CREATED_DATE) VALUES('register-employe', 'Registar empleados', NOW());

/* Add roles */
INSERT INTO HHTEDTROLE(CODE, NAME, CREATED_DATE) VALUES('admin', 'Administrator', NOW());
INSERT INTO HHTEDTROLE(CODE, NAME, CREATED_DATE) VALUES('employee', 'Empleado', NOW());

/* Add functionalities to Role */
INSERT INTO HHTEDTROLFUN(ROLE_ID, FUNCTIONALITY_ID, CREATED_DATE) VALUES (1,1, NOW());

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('admin@hiberus.com', '123', 1, NOW());
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('lfernandez@hiberus.com', '123', 2, NOW());
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('amartinez@hiberus.com', '123', 2, NOW());
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('pgimenez@hiberus.com', '123', 2, NOW());
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('omuenala@hiberus.com', '123', 2, NOW());
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('acordoba@hiberus.com', '123', 2, NOW());
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('candrade@hiberus.com', '123', 2, NOW());
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('eordoñez@hiberus.com', '123', 2, NOW());

/* City */
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('Sevilla', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('Barcelona', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('San Sebastian', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('Granada', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('Valencia', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('Salamanca', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('Madrid', 1, NOW());

/* Position */
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Gerente de cuenta', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Technical Leader', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Director Proyectos Estratégicos', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Director General', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Director People Transformation', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Technical Leader Cloud Services', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Service Manager', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Responsable Departamento de Control', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Director Sector Público', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Director Operaciones', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Manager Recruitment', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Gestión de Talento', 1, NOW());

/* Department */
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Administración', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Control', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Marketing y Business Value', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PMO', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('BU Comunicación', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Recursos Humanos', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Operaciones', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Tecnologías Diferenciales', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Comercial', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Media Labs', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Finanzas y Soporte al Negocio', 1, NOW());

/* Skills */
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Java', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('.NET', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Angular', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PHP', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Spring Boot', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Mysql', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('JPA', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Hibernate', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('React', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Spring MVC', 1, NOW());

/* Certifications */
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Frontend Angular', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Virtualización de Servicios', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('UX y UI', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Desarrollo de Ecommerce', 1, NOW());

/* Projects */
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Gestión Tributaria Madrid', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Portal Madrid.es', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Portal Spain.info', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Tarjeta Ciudadana Zaragoza', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Ayuntamiento de Valencia', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('Administración Electrónica del Gobierno de Aragón', 1, NOW());

/* Employee */
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Luis Mateo', 'Fernandez Calderón', '0369854215', 1, 1, 1, 1, 1, NOW());

INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, IMMEDIATE_CHIEF_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Andrea Lucia', 'Martínez Flores', '0236845212', 2, 2, 2, 1, 2, 1, NOW());

INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, IMMEDIATE_CHIEF_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Pablo José', 'Giménez Alvarez', '0234784125', 3, 3, 3, 1, 3, 1, NOW());

INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, IMMEDIATE_CHIEF_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Oscar Manul', 'Muenala Osmasa', '0854123975', 4, 4, 4, 1, 4, 1, NOW());

INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, IMMEDIATE_CHIEF_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Anuel Miguel', 'Cordoba Soto', '0642513257', 5, 5, 5, 1, 5, 1, NOW());

INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, IMMEDIATE_CHIEF_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Carolina Janeth', 'Andrade Cifuentes', '0741236854', 6, 6, 6, 1, 6, 1, NOW());

INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, IMMEDIATE_CHIEF_ID, USER_ID, CREATED_BY_USER, CREATED_DATE)
VALUES ('Elizabeth María', 'Ordoñez Sincel', '012356874', 7, 7, 7, 1, 7, 1, NOW());

/* Add projects */

INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());

/* */
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());

/* */
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());