/* Add Cities */
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('BARCELONA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('SAN SEBASTIAN', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('GRANADA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('VALENCIA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('SALAMANCA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('MADRID', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('SANTIAGO DE COMPOSTELA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('GALICIA', 1, NOW());
INSERT INTO HHTEDTCITY(NAME, CREATED_BY_USER, CREATED_DATE) VALUES('CANTABRIA', 1, NOW());

/* Add Positions */
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('TECHNICAL LEADER', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR PROYECTOS ESTRATÉGICOS', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR GENERAL', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR PEOPLE TRANSFORMATION', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('TECHNICAL LEADER CLOUD SERVICES', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('SERVICE MANAGER', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('RESPONSABLE DEPARTAMENTO DE CONTROL', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR SECTOR PÚBLICO', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('DIRECTOR OPERACIONES', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MANAGER RECRUITMENT', 1, NOW());
INSERT INTO HHTEDTPOSITION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('GESTIÓN DE TALENTO', 1, NOW());

/* Department */
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('ADMINISTRACIÓN', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('CONTROL', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MARKETING Y BUSINESS VALUE', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PMO', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('BU COMUNICACIÓN', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('RECURSOS HUMANOS', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('OPERACIONES', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('TECNOLOGÍAS DIFERENCIALES', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MEDIA LABS', 1, NOW());
INSERT INTO HHTEDTDEPARTMENT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('FINANZAS Y SOPORTE AL NEGOCIO', 1, NOW());

/* Skills */
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('JAVA', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('.NET', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('ANGULAR', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PHP', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('SPRING BOOT', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MYSQL', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('JPA', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('HIBERNATE', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('REACT', 1, NOW());
INSERT INTO HHTEDTSKILL (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('SPRING MVC', 1, NOW());

/* Projects */
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('GESTIÓN TRIBUTARIA MADRID', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PORTAL MADRID.ES', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('PORTAL SPAIN.INFO', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('TARJETA CIUDADANA ZARAGOZA', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('AYUNTAMIENTO DE VALENCIA', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('ADMINISTRACIÓN ELECTRÓNICA DEL GOBIERNO DE ARAGÓN', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('IOT PARA PUNTOS DE VENTA', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('HIBERUS BANKING SERVICES', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MARKETPLACE', 1, NOW());
INSERT INTO HHTEDTPROJECT (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('CMS', 1, NOW());

/* Certifications */
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('FRONTEND ANGULAR', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('VIRTUALIZACIÓN DE SERVICIOS', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('UX Y UI', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('NODE.JS AVANZADO', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MICROSERVICIOS', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('GESTIÓN DE TRANSACCIONES CON MICROSERVICIOS', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('ORQUESTACIÓN DE SERVICIOS CON KUBERNETES', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('ENTORNOS DE DESARROLLO CON DOCKER', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('CD Y CI CON JENKINS', 1, NOW());
INSERT INTO HHTEDTCERTIFICATION (NAME, CREATED_BY_USER, CREATED_DATE) VALUES ('MACHINE LEARNING', 1, NOW());

/* Employee */
INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('arentero@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Antonio Guillermo', 'Rentero Hereza', '723685412', 2, 2, 2, 2, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ebarbed@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Elena Maria', 'Barbed Mutuberria', '723685412', 3, 3, 3, 3, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('mgarcia@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Mireya Sarah', 'García Latorre', '723685412', 4, 4, 4, 4, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('aesteban@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Adrián Javier', 'Esteban Virto', '723685412', 5, 5, 5, 5, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ssantolaria@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Sara Eva', 'Santolaria Menéndez', '723685412', 6, 6, 6, 6, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('palgas@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Pilar Alexandra', 'Algas García', '723685412', 7, 7, 7, 7, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ohierro@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Oliver Sergio', 'Hierro Gil', '723685412', 8, 8, 8, 8, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('vsanchez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Víctor Jesús', 'Sanchez Mingote', '723685412', 9, 9, 9, 9, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('jmorales@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('José Luis', 'Morales Zapata', '723685412', 10, 10, 10, 10, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('vgimeno@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Víctor José', 'Gimeno Barco', '723685412', 1, 2, 3, 11, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('lruiz@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Luis Miguel', 'Ruiz Latorre', '723685412', 4, 5, 6, 12, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('lgonzalez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Jose Luis', 'Gonzalez Pereda', '723685412', 7, 8, 9, 13, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ddomeque@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Daniel Iván', 'Domeque Romero', '723685412', 10, 1, 2, 14, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('jrubio@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Jose Eugenio', 'Rubio Ramírez', '723685412', 10, 9, 8, 15, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('pmartinez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Pablo Diego', 'Martinez Martín', '723685412', 7, 6, 5, 16, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('mmontane@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Mireia Maria', 'Montané Rox', '723685412', 4, 3, 2, 17, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('cpena@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Claudio David', 'Peña Sancho', '723685412', 1, 2, 4, 18, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('cgarces@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Carlos Javier', 'Garcés Prenafeta', '723685412', 6, 8, 10, 19, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('scasado@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('David Mariano', 'Casado Minoli', '723685412', 1, 3, 5, 20, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('icarcas@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Ignacio Fernando', 'Carcas Solano', '723685412', 7, 9, 1, 21, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('edeldiego@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Eduardo Cristóbal', 'Del Diego Lopez', '723685412', 10, 8, 6, 22, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('jrodriguez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Jose David', 'Rodriguez Sancha', '723685412', 4, 2, 10, 23, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('jtafalla@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Javier Antonio', 'Tafalla Moriano', '723685412', 9, 7, 5, 24, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ejimenez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Eduardo Borja', 'Jimenez Sanmartin', '723685412', 3, 1, 9, 25, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('bblasco@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Beatriz Laura', 'Blasco Labrador', '723685412', 2, 1, 4, 26, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('cmarzo@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Carlos David', 'Marzo Torres', '723685412', 3, 6, 5, 27, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('lgayarre@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Lorenzo Aitor', 'Gayarre Canales', '723685412', 8, 7, 10, 28, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('ahernandez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Alejandro Manuel', 'Hernández Giménez', '723685412', 9, 2, 1, 29, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('nsamperiz@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Natalia Laura', 'Samperiz Anchuelo', '723685412', 1, 3, 2, 30, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('mgonzalez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Fernando Manuel', 'Gonzalez Vicente', '723685412', 4, 5, 7, 31, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('mrodriguez@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Miguel Jorge', 'Rodriguez Usón', '723685412', 8, 10, 9, 32, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('aromero@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Andrés Rafael', 'Romero Flores', '723685412', 2, 4, 1, 33, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('rortiz@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Ruben Juan', 'Ortiz Perez', '723685412', 3, 6, 8, 34, 1, NOW(), 1);

INSERT INTO HHTEDTUSER(EMAIL, PASSWORD, ROLE_ID, CREATED_DATE) VALUES ('adomingo@hiberus.com', '$argon2id$v=19$m=4096,t=3,p=1$COpt6Zww/UQu6RWD9M6S7Q$M8/J67t6DgYRRfsvlydV2x0hZ6CQIbbdUU9HqiWznOs', 2, NOW());
INSERT INTO HHTEDTEMPLOYEE (NAME, LAST_NAME, PHONE, CITY_ID, POSITION_ID, DEPARTMENT_ID, USER_ID, CREATED_BY_USER, CREATED_DATE, IMMEDIATE_CHIEF_ID)
VALUES ('Sergio Juan', 'Domingo López', '723685412', 5, 7, 10, 35, 1, NOW(), 1);


/* Add projects to employee 2*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());
/* Add certification to employee 2*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());
/* Add skills to employee 2*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,2,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,2,1,NOW());

/* Add projects to employee 3*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,3,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,3,1,NOW());
/* Add certification to employee 3*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (3,3,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (2,3,1,NOW());
/* Add skills to employee 3*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,3,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,3,1,NOW());

/* Add projects to employee 4*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,4,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,4,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,4,1,NOW());

/* Add certification to employee 4*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (4,4,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (1,4,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (3,4,1,NOW());
/* Add skills to employee 4*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,4,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,4,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,4,1,NOW());

/* Add projects to employee 5*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,5,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,5,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,5,1,NOW());
/* Add certification to employee 5*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (9,5,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (5,5,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (3,5,1,NOW());
/* Add skills to employee 5*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,5,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,5,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,5,1,NOW());

/* Add projects to employee 6*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,6,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,6,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,6,1,NOW());
/* Add certification to employee 6*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (7,6,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (6,6,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (2,6,1,NOW());
/* Add skills to employee 6*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,6,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,6,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,6,1,NOW());

/* Add projects to employee 7*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,7,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,7,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,7,1,NOW());
/* Add certification to employee 7*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (8,7,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (10,7,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (1,7,1,NOW());
/* Add skills to employee 7*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,7,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,7,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,7,1,NOW());

/* Add projects to employee 8*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,8,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,8,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,8,1,NOW());
/* Add certification to employee 8*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (7,8,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (9,8,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (2,8,1,NOW());
/* Add skills to employee 8*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,8,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,8,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,8,1,NOW());

/* Add projects to employee 9*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,9,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,9,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,9,1,NOW());
/* Add certification to employee 9*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (4,9,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (5,9,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (6,9,1,NOW());
/* Add skills to employee 9*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,9,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,9,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,9,1,NOW());

/* Add projects to employee 10*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,10,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,10,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,10,1,NOW());
/* Add certification to employee 10*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (3,10,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (6,10,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (5,10,1,NOW());
/* Add skills to employee 10*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,10,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,10,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,10,1,NOW());

/* Add projects to employee 11*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,11,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,11,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,11,1,NOW());
/* Add certification to employee 11*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (4,11,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (5,11,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (6,11,1,NOW());
/* Add skills to employee 11*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,11,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,11,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,11,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,11,1,NOW());

/* Add projects to employee 12*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,12,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,12,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,12,1,NOW());
/* Add certification to employee 12*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (7,12,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (6,12,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (5,12,1,NOW());
/* Add skills to employee 12*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,12,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,12,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,12,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,12,1,NOW());

/* Add projects to employee 13*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,13,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,13,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,13,1,NOW());
/* Add certification to employee 13*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (8,13,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (10,13,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (2,13,1,NOW());
/* Add skills to employee 13*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,13,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,13,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,13,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,13,1,NOW());

/* Add projects to employee 14*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,14,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,14,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,14,1,NOW());
/* Add certification to employee 14*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (7,14,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (9,14,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (1,14,1,NOW());
/* Add skills to employee 14*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,14,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,14,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,14,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,14,1,NOW());

/* Add projects to employee 15*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,15,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,15,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,15,1,NOW());
/* Add certification to employee 15*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (4,15,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (2,15,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (10,15,1,NOW());
/* Add skills to employee 15*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,15,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,15,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,15,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,15,1,NOW());

/* Add projects to employee 16*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,16,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,16,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,16,1,NOW());
/* Add certification to employee 16*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (3,16,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (1,16,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (9,16,1,NOW());
/* Add skills to employee 16*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,16,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,16,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,16,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,16,1,NOW());

/* Add projects to employee 17*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,17,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,17,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,17,1,NOW());
/* Add certification to employee 17*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (3,17,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (6,17,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (5,17,1,NOW());
/* Add skills to employee 17*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,17,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,17,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,17,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,17,1,NOW());

/* Add projects to employee 18*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,18,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,18,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,18,1,NOW());
/* Add certification to employee 18*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (3,18,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (6,18,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (8,18,1,NOW());
/* Add skills to employee 18*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,18,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,18,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,18,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,18,1,NOW());

/* Add projects to employee 19*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,19,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,19,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,19,1,NOW());
/* Add certification to employee 19*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (4,19,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (5,19,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (7,19,1,NOW());
/* Add skills to employee 19*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,19,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,19,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,19,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,19,1,NOW());

/* Add projects to employee 20*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,20,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (8,20,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,20,1,NOW());
/* Add certification to employee 20*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (7,20,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (6,20,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (4,20,1,NOW());
/* Add skills to employee 20*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,20,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (5,20,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (3,20,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,20,1,NOW());

/* Add projects to employee 21*/
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (9,21,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (7,21,1,NOW());
INSERT INTO HHTEDTEMPPRO (PROJECT_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (10,21,1,NOW());
/* Add certification to employee 21*/
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (8,21,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (5,21,1,NOW());
INSERT INTO HHTEDTEMPCER (CERTIFICATION_ID , EMPLOYEE_ID , CREATED_BY_USER, CREATED_DATE) VALUES (3,21,1,NOW());
/* Add skills to employee 21*/
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (6,21,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (4,21,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (1,21,1,NOW());
INSERT INTO HHTEDTEMPSKI (SKILL_ID, EMPLOYEE_ID, CREATED_BY_USER, CREATED_DATE) VALUES (2,21,1,NOW());