select * from HHTEDTEMPLOYEE h;
select * from HHTEDTUSER h;
select * from HHTEDTCITY h ;
select * from HHTEDTPOSITION h ;
select * from HHTEDTDEPARTMENT h 
select * from HHTEDTSKILL h2 ;
select * from HHTEDTCERTIFICATION h ;
select * from HHTEDTPROJECT h ;

UPDATE HHTEDTEMPLOYEE SET CITY_ID  = 1, POSITION_ID = 2, DEPARTMENT_ID = 3 where EMPLOYEE_ID = 1;
UPDATE HHTEDTEMPLOYEE SET CITY_ID  = 2, POSITION_ID = 3, DEPARTMENT_ID = 3 where EMPLOYEE_ID = 2;
UPDATE HHTEDTEMPLOYEE SET CITY_ID  = 1, POSITION_ID  = 2, DEPARTMENT_ID = 6 where EMPLOYEE_ID = 3;
UPDATE HHTEDTEMPLOYEE SET CITY_ID  = 2, POSITION_ID  = 2, DEPARTMENT_ID  = 6 where EMPLOYEE_ID = 4;

SELECT * from HHTEDTEMPPRO h ;
SELECT * from HHTEDTEMPSKI h ;
SELECT * from HHTEDTEMPCER h ;

UPDATE HHTEDTEMPPRO SET STATUS = 0 WHERE EMPLOYEE_ID = 2 AND PROJECT_ID = 1;