USE HHTEDDBEMPLOYEEDIRECTORY;

/* Role functionalities */
ALTER TABLE HHTEDTROLFUN
ADD CONSTRAINT HHTEDRFKROLFUNPKROL
FOREIGN KEY (ROLE_ID) REFERENCES HHTEDTROLE (ROLE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTROLFUN
ADD CONSTRAINT HHTEDRFKROLFUNPKFUN
FOREIGN KEY (FUNCTIONALITY_ID) REFERENCES HHTEDTFUNCTIONALITY (FUNCTIONALITY_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - City */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKCIT
FOREIGN KEY (CITY_ID) REFERENCES HHTEDTCITY (CITY_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - Position */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKPOS
FOREIGN KEY (POSITION_ID) REFERENCES HHTEDTPOSITION (POSITION_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - Department */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKDEP
FOREIGN KEY (DEPARTMENT_ID) REFERENCES HHTEDTDEPARTMENT (DEPARTMENT_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - Immediate Chief */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPIMMCHIPKEMP
FOREIGN KEY (IMMEDIATE_CHIEF_ID) REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* User - Role */
ALTER TABLE HHTEDTUSER
ADD CONSTRAINT HHTEDRFKUSEPKROL
FOREIGN KEY (ROLE_ID) REFERENCES HHTEDTROLE (ROLE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* User - Employee */
ALTER TABLE HHTEDTUSER
ADD CONSTRAINT HHTEDRFKUSEPKEMP
FOREIGN KEY (EMPLOYEE_ID)
REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee skills */
ALTER TABLE HHTEDTEMPSKI
ADD CONSTRAINT HHTEDRFKEMPSKIPKSKI
FOREIGN KEY (SKILL_ID) REFERENCES HHTEDTSKILL (SKILL_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPSKI
ADD CONSTRAINT HHTEDRFKEMPSKIPKEMP
FOREIGN KEY (EMPLOYEE_ID) REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee certifications */
ALTER TABLE HHTEDTEMPCER
ADD CONSTRAINT HHTEDRFKEMPCERPKCER
FOREIGN KEY (CERTIFICATION_ID) REFERENCES HHTEDTCERTIFICATION (CERTIFICATION_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPCER
ADD CONSTRAINT HHTEDRFKEMPCERPKEMP
FOREIGN KEY (EMPLOYEE_ID) REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee projects */
ALTER TABLE HHTEDTEMPPRO
ADD CONSTRAINT HHTEDRFKEMPPROPKPRO
FOREIGN KEY (PROJECT_ID) REFERENCES HHTEDTPROJECT (PROJECT_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPPRO
ADD CONSTRAINT HHTEDRFKEMPPROPKEMP
FOREIGN KEY (EMPLOYEE_ID) REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;