USE HHTEDDB;

/* Role functionalities */
ALTER TABLE HHTEDTROLFUN
ADD CONSTRAINT HHTEDRFKROLFUNPKROL
FOREIGN KEY (ROLE_ID) REFERENCES HHTEDTROLE (ROLE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTROLFUN
ADD CONSTRAINT HHTEDRFKROLFUNPKFUN
FOREIGN KEY (FUNCTIONALITY_ID) REFERENCES HHTEDTFUNCTIONALITY (FUNCTIONALITY_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - City */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKCIT
FOREIGN KEY (CITY_ID) REFERENCES HHTEDTCITY (CITY_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - Position */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKPOS
FOREIGN KEY (POSITION_ID) REFERENCES HHTEDTPOSITION (POSITION_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - Department */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKDEP
FOREIGN KEY (DEPARTMENT_ID) REFERENCES HHTEDTDEPARTMENT (DEPARTMENT_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - Immediate Chief */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPIMMCHIPKEMP
FOREIGN KEY (IMMEDIATE_CHIEF_ID) REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee - User */
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKUSE
FOREIGN KEY (USER_ID)
REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* User - Role */
ALTER TABLE HHTEDTUSER
ADD CONSTRAINT HHTEDRFKUSEPKROL
FOREIGN KEY (ROLE_ID) REFERENCES HHTEDTROLE (ROLE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee skills */
ALTER TABLE HHTEDTEMPSKI
ADD CONSTRAINT HHTEDRFKEMPSKIPKSKI
FOREIGN KEY (SKILL_ID) REFERENCES HHTEDTSKILL (SKILL_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPSKI
ADD CONSTRAINT HHTEDRFKEMPSKIPKEMP
FOREIGN KEY (EMPLOYEE_ID) REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee certifications */
ALTER TABLE HHTEDTEMPCER
ADD CONSTRAINT HHTEDRFKEMPCERPKCER
FOREIGN KEY (CERTIFICATION_ID) REFERENCES HHTEDTCERTIFICATION (CERTIFICATION_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPCER
ADD CONSTRAINT HHTEDRFKEMPCERPKEMP
FOREIGN KEY (EMPLOYEE_ID) REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Employee projects */
ALTER TABLE HHTEDTEMPPRO
ADD CONSTRAINT HHTEDRFKEMPPROPKPRO
FOREIGN KEY (PROJECT_ID) REFERENCES HHTEDTPROJECT (PROJECT_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPPRO
ADD CONSTRAINT HHTEDRFKEMPPROPKEMP
FOREIGN KEY (EMPLOYEE_ID) REFERENCES HHTEDTEMPLOYEE (EMPLOYEE_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

/* Audit relationships */
ALTER TABLE HHTEDTROLE
ADD CONSTRAINT HHTEDRFKROLPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTROLE
ADD CONSTRAINT HHTEDRFKROLPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTFUNCTIONALITY
ADD CONSTRAINT HHTEDRFKFUNPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTFUNCTIONALITY
ADD CONSTRAINT HHTEDRFKFUNPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTROLFUN
ADD CONSTRAINT HHTEDRFKROLFUNPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTROLFUN
ADD CONSTRAINT HHTEDRFKROLFUNPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTCITY
ADD CONSTRAINT HHTEDRFKCITPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTCITY
ADD CONSTRAINT HHTEDRFKCITPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTPROJECT
ADD CONSTRAINT HHTEDRFKPROPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTPROJECT
ADD CONSTRAINT HHTEDRFKPROPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTPOSITION
ADD CONSTRAINT HHTEDRFKPOSPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTPOSITION
ADD CONSTRAINT HHTEDRFKPOSPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTDEPARTMENT
ADD CONSTRAINT HHTEDRFKDEPPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTDEPARTMENT
ADD CONSTRAINT HHTEDRFKDEPPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTSKILL
ADD CONSTRAINT HHTEDRFKSKIPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTSKILL
ADD CONSTRAINT HHTEDRFKSKIPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTCERTIFICATION
ADD CONSTRAINT HHTEDRFKCERPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTCERTIFICATION
ADD CONSTRAINT HHTEDRFKCERPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTEMPLOYEE
ADD CONSTRAINT HHTEDRFKEMPPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTUSER
ADD CONSTRAINT HHTEDRFKUSEPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTUSER
ADD CONSTRAINT HHTEDRFKUSEPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPSKI
ADD CONSTRAINT HHTEDRFKEMPSKIPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTEMPSKI
ADD CONSTRAINT HHTEDRFKEMPSKIPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPCER
ADD CONSTRAINT HHTEDRFKEMPCERPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTEMPCER
ADD CONSTRAINT HHTEDRFKEMPCERPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HHTEDTEMPPRO
ADD CONSTRAINT HHTEDRFKEMPPROPKCREATEDUSER
FOREIGN KEY (CREATED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE HHTEDTEMPPRO
ADD CONSTRAINT HHTEDRFKEMPPROPKMODIFIEDUSER
FOREIGN KEY (LAST_MODIFIED_BY_USER) REFERENCES HHTEDTUSER (USER_ID)
ON DELETE NO ACTION ON UPDATE NO ACTION;